### ISSUE TITLE
Add an endpoint to calculate Inflation.

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#10]
**Note**

- Inflation lowers purchasing power of the rupee. As a result, whenever a saving plan is being chalked out, inflation is one of the factors that has to be taken into account.

- Inflation is calculated as - Future amount = Present amount * (1+inflation rate) ^number of years

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/inflation` in the `main.py` file with properly.

**Comment by melencholicmice** [comment]
Hello , I would like to work on this issue. If this is available can you please assign it to me

**Comment by ighoshsubho** [comment]
Go ahead @melencholicmice

**Comment by melencholicmice** [comment]
added commits in pull request [#15](https://github.com/Clueless-Community/fintech-api/pull/15) that resolves this issue. Can you please review it. If you want some changes do let me know. Thank you
