### ISSUE TITLE
add endpoint to calculate real gdp

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#103]
<img width="165" alt="Screenshot 2022-12-18 at 9 16 07 AM" src="https://user-images.githubusercontent.com/41890434/208280345-e33ac8bc-6ddf-45d3-9f89-f7e667dfa8de.png">

**Comment by chandansgowda** [comment]
Shall I take this up ?

**Comment by nikhil25803** [comment]
Sure @chandansgowda :))
