### ISSUE TITLE
endpoint to calculate future value of annuity due

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#106]
The Future Value of Annuity Due due is the value of consolidated payments at a date in the future, considering a fixed return or discount rate. 

FVA Due = P * {(1 + r) n - 1) * (1 + r) / r}

P denotes Periodic Payment
n denotes the Number of Periods
r denotes the Effective interest rate

**Comment by nikhil25803** [comment]
Go ahead :))

**Comment by ShamanthVallem** [comment]
@nikhil25803 Along with **FVA due** endpoint can i add **future value of ordinary annuity endpoint**
fva ordinary: payments made are assumed to be at end of the year
fva annuity: paymnets made are assumed to be begining of the year

formula:  P * [(1 + i)n – 1] / i

**Comment by nikhil25803** [comment]
Sure @ShamanthVallem, go ahead :))
