### ISSUE TITLE
Add an endpoint to calculate Compounded Annual Growth Rate (CAGR)

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#11]
**Note**

- This is used to indicate the return on an investment over a period. It is also the best tool to compare returns of two different asset classes - for instance gold/equity or equity/real estate. 

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/cagr` in the `main.py` file with properly.

**Comment by Lakshya-30** [comment]
May I work on this issue?

**Comment by ighoshsubho** [comment]
Go ahead @Lakshya-30
