### ISSUE TITLE
Add endpint to calculate lease.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/fintech-api#117]
### What bug or feature you wants to report.

+ The effective interest rate or monthly payment for a lease can both be determined using the lease calculator.

![image](https://user-images.githubusercontent.com/93156825/209367717-d9fbb6f4-7ad2-4e6e-83bb-569cff082de4.png)

**Comment by ShamanthVallem** [comment]
@nikhil25803 Is this issue open? If yes I would like to work on this

**Comment by nikhil25803** [comment]
Sure, go ahead @ShamanthVallem :))
