### ISSUE TITLE
Add endpoint to calculate retention ratio

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#119]
<img width="467" alt="Screenshot 2022-12-24 at 9 13 42 AM" src="https://user-images.githubusercontent.com/41890434/209420068-01ba3e58-0d0a-43bc-b67c-5d5083602415.png">

**Comment by chandansgowda** [comment]
Shall I take this up ?

**Comment by nikhil25803** [comment]
Go ahead :)
