### ISSUE TITLE
Add an endpoint to calculate Effective Annual Rate

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#12]
**Note**

- Generally, an investment's annual rate of return is different from the nominal rate of return when compounding occurs more than once a year (quarterly, half-yearly).

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/effective_annual_rate` in the `main.py` file properly.

**Comment by ighoshsubho** [comment]
sure @melencholicmice go for it!

**Comment by melencholicmice** [comment]
Hello sir , I have resolved this issue in PR [#15](https://github.com/Clueless-Community/fintech-api/pull/15). The formula for Effective Annual Rate is
![Screenshot from 2022-12-05 02-48-33](https://user-images.githubusercontent.com/109169835/205516223-6b35823c-b89d-4ef6-9575-0ab6d78e566a.png)

if you want difernt parameters or find any mistake in formula  or output format please let me know i will make necessary changes

Thank you
