### ISSUE TITLE
Add Endpoint to calculate Balloon Balance of a Loan

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#120]
<img width="467" alt="Screenshot 2022-12-24 at 9 15 46 AM" src="https://user-images.githubusercontent.com/41890434/209420118-f2752063-4017-4590-897b-8423f17a5c42.png">

**Comment by chandansgowda** [comment]
Please assign me

**Comment by nikhil25803** [comment]
@chandansgowda, isn't the balloon balance is calculated the same way the remaining balance does?
As submitted in the issue #121

**Comment by chandansgowda** [comment]
Yeahh @nikhil25803 
But in the formula cheatsheat which I'm referring, both are mentioned.

**Comment by nikhil25803** [comment]
Both are the same ig, add this one only. @chandansgowda
