### ISSUE TITLE
Endpoint to calculate Weighted average

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#122]
### What bug or feature you wants to report.

<img width="234" alt="Screenshot 2022-12-24 162611" src="https://user-images.githubusercontent.com/73659072/209432823-c85c3452-a615-45d4-b842-3383abf0d565.png">

**Comment by ShamanthVallem** [comment]
Can I work on this?

**Comment by nikhil25803** [comment]
Go ahead :)

**Comment by ShamanthVallem** [comment]
@nikhil25803 
In the helper_function.py, while defining a function, can I take 'list' as a parameter or should I use space-separated numbers??

**Comment by nikhil25803** [comment]
> e-separate

No, It is not a good practice to pass a list as a parameter, use & separate parameters (query parameters).
You can also use *args functionality.
Merged the PR for now, but fix it asap, and make another PR 
@ShamanthVallem
