### ISSUE TITLE
Add an endpoint to calculate Loan to Value

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#124]
**Note**
![image](https://user-images.githubusercontent.com/89008784/209447443-97ae09e1-a2ae-4445-a759-315ae163e595.png)

- Add an endpoint to calculate Loan to Value.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/loan-to-value` in the `main.py` file with properly.

**Comment by vamsikrishnarh7** [comment]
hey @nikhil25803
Please assign this to me :)

**Comment by nikhil25803** [comment]
Go ahead :))
