### ISSUE TITLE
Add an endpoint to calculate the Year Over Year Growth 

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#127]
**Note**
**Formula :**
`YOY = (later period value - earlier period value) / earlier period value`
- Add an endpoint to calculate Year over year growth.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/year-to-year` in the `main.py` file with properly.

**Comment by vamsikrishnarh7** [comment]
hey @nikhil25803 please assign this to me :)

**Comment by nikhil25803** [comment]
Go ahead @vamsikrishnarh7 :))
