### ISSUE TITLE
add an endpoint to calculate Tax Equivalent Yield

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#128]
**Formula**
`Tax Equivalent Yield = tax free yield / ( 1 - tax rate)`

- Add an endpoint to calculate tax equivalent yield.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/tax-equi-yield` in the `main.py` file with properly.

**Comment by vamsikrishnarh7** [comment]
hey @nikhil25803 please assign this to me :)

**Comment by nikhil25803** [comment]
Sure @vamsikrishnarh7
