### ISSUE TITLE
Add an endpoint to calculate Loan EMI

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#13]
**Note**

- Equated monthly instalments (EMIs) are common in our day-to-day life. At the time of taking a loan, we are shown a neat A4 size paper explaining the EMI structure in a simplified manner.  It is generally an unequal combination of principal and interest payments. 

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/loan_emi` in the `main.py` file with properly.

**Comment by DarK-VEnOM-16** [comment]
@ighoshsubho 
I would like to solve this issue.
Please assign this issue to me.

**Comment by ighoshsubho** [comment]
Go ahead @DarK-VEnOM-16

**Comment by DarK-VEnOM-16** [comment]
EMI = P * [( r * (1 + r)^n)) / ((1 + r)^n - 1)]
where:
P = Princiapl amount borrowed
r = Periodic monthly interest rate
n = Total number of monthly payments

Should I use this formula to calculate EMI
