### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/fintech-api#130]
### What bug or feature you wants to report.

In the Main [Readme.md](https://github.com/Clueless-Community/fintech-api/blob/main/README.md), After clicking on the conribution keyword, it redirects to `Flutter UI contribution guidelines` but it should redirect to `fintech-api` contribution guidelines.
![Screenshot_20221226_012525](https://user-images.githubusercontent.com/98400348/209481023-d7bea11a-8b3b-4b70-8d24-6ca7aa66f34a.png)

**Comment by RavindraP04** [comment]
Please assign this to me

**Comment by nikhil25803** [comment]
Thanks for noticing it out :))

**Comment by RavindraP04** [comment]
Done #134 

> Thanks for noticing it out :))
