### ISSUE TITLE
Add an endpoint to calculate Perpetuity Payment

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#136]
**Formula**
`Perpetuity Payment = Present Value x rate`

- Add an endpoint to calculate Perpetuity Payment.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/perpetuity-payment` in the `main.py` file with properly.

**Comment by nikhil25803** [comment]
Go ahead @vamsikrishnarh7 !!
