### ISSUE TITLE
Add and endpoint to calculate Yield to Maturity

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#137]
![image](https://user-images.githubusercontent.com/89008784/209669096-54a3c72f-9411-415c-b55c-eb2a77f81b74.png)

- Add an endpoint to calculate yield to maturity.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/yield-to-maturity` in the `main.py` file with properly.

**Comment by nikhil25803** [comment]
Looks good, go ahead and add this endpoint :))
