### ISSUE TITLE
Endpoint to calculate Profitability index

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#146]
### What bug or feature you wants to report.

The profitability index (PI) describes an index representing the relationship between a proposed project's costs and benefits.

<img width="432" alt="profitability_index" src="https://user-images.githubusercontent.com/73659072/210064604-54041372-4f86-4c8f-88e9-459f26a8bd25.png">

**Comment by ShamanthVallem** [comment]
And to calculate the PV of future cash flows this formula is used:

![IMG_20221230_164959](https://user-images.githubusercontent.com/73659072/210064951-3d57dac6-c72f-4cdf-be89-c542b3e4c271.jpg)

**Comment by nikhil25803** [comment]
Looks good, go ahead:))
