### ISSUE TITLE
Rename the endpoints that do not follow the convention.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/fintech-api#148]
### What bug or feature you wants to report.

**Note**
+ Go through all the endpoints, and rename them in snake-case format (eg. `fintech_api`)
+ No `-` or capital letters, PascalCase is allowed.

**Comment by vamsikrishnarh7** [comment]
hey @nikhil25803 please assign this to me

**Comment by nikhil25803** [comment]
Go ahead @vamsikrishnarh7 :))
