### ISSUE TITLE
Add an endpoint to calculate Zero Coupon Bond Value

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#152]
![image](https://user-images.githubusercontent.com/89008784/210171810-39958731-bc2a-4e62-96de-1cab5aae15d3.png)

- Add an endpoint to calculate `zero coupon bond value`.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/zero_coupon_bond_value` in the main.py file with properly.

**Comment by vamsikrishnarh7** [comment]
hey @nikhil25803 please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead
