### ISSUE TITLE
Add endpoint to calculate Zero Coupon Bond Effective Yield

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#153]
![image](https://user-images.githubusercontent.com/89008784/210172003-45e9c167-e943-4881-b34b-c499c3771054.png)

- Add an endpoint to `Zero Coupon Bond Effective Yield`.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/zero_coupon_bond_effective_yield` in the `main.py` file with properly.

**Comment by nikhil25803** [comment]
Go ahead @vamsikrishnarh7 :))
