### ISSUE TITLE
Add Endpoint to calculate Bid Ask Spread

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#156]
### What bug or feature you wants to report.

The bid ask spread formula is the difference between the asking price and bid price of a particular investment. The bid ask spread may be used for various investments and is primarily used in investments that sell on an exchange.

Bid-Ask Spread = Ask Price - Bid Price

**Comment by chandansgowda** [comment]
Please assign me

**Comment by nikhil25803** [comment]
Hey @chandansgowda, 3 of your issues are still open? Any updates?

**Comment by chandansgowda** [comment]
Hey @nikhil25803 
I'm busy since my sem end are going on and other projects have come. Can I unassign myself ?

**Comment by nikhil25803** [comment]
@chandansgowda, your call :))
You may make the PRs after exams and all, was just looking for an update.
