### ISSUE TITLE
Add endpoint to calculate Yield to Maturity

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#157]
### What bug or feature you wants to report.

The yield to maturity formula is used to calculate the yield on a bond based on its current price on the market. The yield to maturity formula looks at the effective yield of a bond based on compounding as opposed to the simple yield which is found using the dividend yield formula.

![Screenshot 2023-01-01 at 8 54 41 PM](https://user-images.githubusercontent.com/41890434/210176013-6499b65b-4427-4926-a961-09163d4f902a.png)

**Comment by chandansgowda** [comment]
Please assign me

**Comment by nikhil25803** [comment]
This endpoint is already added @chandansgowda, please cross-verify.
