### ISSUE TITLE
Group Endpoints into different categories

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#159]
### What bug or feature you wants to report.

As of now, all the endpoints are in one file. These endpoints can be classified into different categories like:

- General Finance
- Banking
- Stocks/Bonds
- Corporate Finance
- Financial Markets

**Comment by nikhil25803** [comment]
Great idea, do it resposibly.

**Comment by chandansgowda** [comment]
Hey, @nikhil25803 
Sorry I wont be able to work on this issue since I'm not sure about which categories the each formula belongs to.
Thanks
