### ISSUE TITLE
Typo in Program workflow

### ISSUE THREAD

**Issue by satyampsoni** [Clueless-Community/fintech-api#161]
There should be `simple_interest_rate()` at the location provided.

Ref:
![image](https://user-images.githubusercontent.com/94950988/210200710-5041981b-549f-4e4d-9139-bf0a05f26912.png)
 link to page:
https://github.com/Clueless-Community/fintech-api/blob/main/CONTRIBUTING.md#project-worflow

**Comment by nikhil25803** [comment]
Fix it :')

**Comment by satyampsoni** [comment]
Done, pls review and merge.
