### ISSUE TITLE
Endpoint to calculate net present value

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#165]
### What bug or feature you wants to report.

Net Present Value (NPV) is the value of all future cash flows over the entire life of an investment discounted to the present
Formula:
<img width="675" alt="net_present_value" src="https://user-images.githubusercontent.com/73659072/210371410-e1dbc0e5-cf7c-41d3-ac54-e2ac0aace0e6.png">

**Comment by nikhil25803** [comment]
Looks good, go ahead.
