### ISSUE TITLE
Add endpoint to calculate yield to maturity

### ISSUE THREAD

**Issue by devgithubsharma** [Clueless-Community/fintech-api#172]
### What bug or feature you wants to report.

![Screenshot (28)](https://user-images.githubusercontent.com/96568994/211202795-bb3641f3-1225-4eda-9343-1ddb7d268c6d.png)

**Comment by devgithubsharma** [comment]
I think we can use this formula in the simplified form to calculate yield to maturity

**Comment by nikhil25803** [comment]
Hey @devgithubsharma, this endpoint has already been added.
