### ISSUE TITLE
Add Endpoint for Leverage Ratio

### ISSUE THREAD

**Issue by amitbatra31** [Clueless-Community/fintech-api#173]
- Which endpoint you are willing to add?
   Endpoint to calculate Leverage ratio
- Reference formula for the calculation.
   There are two forumulas to calculate leverage ratio
   
![image](https://user-images.githubusercontent.com/75168062/211326865-e1c06f16-02c6-401a-a37d-cf80ada60ceb.png)
and 
![image](https://user-images.githubusercontent.com/75168062/211326900-62a69a0c-9f60-4596-9eb3-94916bac15f5.png)

- Name of the endpoint you want to suggest.
/leverage_ratio_income : to calculate using first formula
/leverage_ratio_equity: to calucalate using second

**Comment by nikhil25803** [comment]
Looks god, go ahead and make a PR.
