### ISSUE TITLE
Present Value of an Annuity Due 

### ISSUE THREAD

**Issue by suvamita** [Clueless-Community/fintech-api#176]
### What bug or feature you wants to report.

The present value of annuity due is a calculation that estimates the value of an investment that would begin right away based on future payments.
Present value of an Annuity Due = amount of each annuity * [(1 – (1 / (1 + interest rate) ^ no. of periods))/ interest rate] * (1 + interest rate)
Please assign me this issue.

**Comment by nikhil25803** [comment]
Looks good, go ahead :))
