### ISSUE TITLE
Endpoint to calculate Number of Periods - PV & FV

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#183]
- This formula is used to calculate the length of time a present value would need to reach the future value, given a certain interest rate.
- Perform all the calculations in `function.py` file present in helpers folder
- Create the endpoint `no-of-periods` in `main.py` file and return the required result in proper format
- Formula : 
![no-of-periods](https://financeformulas.net/formulaimages/Solve%20for%20n%20-%20Annuity%20(PV)%201.gif)

**Comment by thecodermaniac** [comment]
i will work on the issue pls assign me this issue

**Comment by thecodermaniac** [comment]
https://github.com/Clueless-Community/fintech-api/pull/188  merge the PR if no further changes are required

**Comment by ighoshsubho** [comment]
great @thecodermaniac go ahead! :)

**Comment by ighoshsubho** [comment]
Ya no more changes are required, it looks good!
