### ISSUE TITLE
Endpoint to calculate Balloon Loan

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#184]
- The balloon loan payment formula is used to calculate the payments on a loan that has a balance remaining after all periodic payments are made.
- Perform all the calculations in `function.py` file present in helpers folder
- Create the endpoint `balloon-loan` in `main.py` file and return the required result in proper format

**Comment by itsmegarvi** [comment]
I will like to work on this

**Comment by ighoshsubho** [comment]
sure go ahead @itsmegarvi

**Comment by itsmegarvi** [comment]
I am still working on this may I know why this issue was closed

**Comment by ighoshsubho** [comment]
Ya, go ahead Garvit, just a random issue. Never mind...
