### ISSUE TITLE
Endpoint to calculate Diluted Earnings per Share

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#185]
- Diluted earnings per share, or Diluted EPS, is a firm's net income divided by the sum of its average shares and other convertible instruments.
- Perform all the calculations in `function.py` file present in the helpers folder
- Create the endpoint `diluted-earnings-per-share` in the `main.py` file and return the required result in a proper format

**Comment by jeicho123** [comment]
I can help implement the function for Diluted EPS

**Comment by jeicho123** [comment]
how do i test btw? kind of new to api

**Comment by ighoshsubho** [comment]
This is a friendly reminder that today is the last day to contribute to the Diversion event. We appreciate your participation and support in making this event a success.

Please make sure to submit your contributions by 6 PM today. Any submissions received after that time will not be accepted.

**Comment by ighoshsubho** [comment]
Sure, @D4nisBag go ahead! :)

**Comment by D4nisBag** [comment]
done, PR #221
