### ISSUE TITLE
Indentation error in main.py at asset_turnover_ratio 

### ISSUE THREAD

**Issue by itsmegarvi** [Clueless-Community/fintech-api#186]
Indentation error in main.py at asset_turnover_ratio (line 1752)

![image](https://user-images.githubusercontent.com/70941313/216848587-a909d4fd-23f7-42a9-a1ed-938de109a7cc.png)

**Comment by ighoshsubho** [comment]
Go ahead and resolve it! :)

**Comment by itsmegarvi** [comment]
Thanks :)
