### ISSUE TITLE
Endpoint to calculate Mortgage Amortization

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#189]
- The Mortgage Amortization Calculation provides an annual or monthly amortization schedule for a mortgage loan.
- Perform all the calculations in the `function.py` file present in the helpers folder
- Create the endpoint `mortgage-amortization` in the `main.py` file and return the required result in a proper format

**Comment by enockzaake** [comment]
Hello, I would like to work on this.

**Comment by ighoshsubho** [comment]
sure @enockzaake, go ahead! :)
