### ISSUE TITLE
Endpoint to calculate 401K

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#190]
- The 401(k) Calculation can estimate a 401(k) balance at retirement as well as distributions in retirement based on income, contribution percentage, age, salary increase, and investment return.
- Perform all the calculations in the `function.py` file present in the helpers folder
- Create the endpoint `401k` in the `main.py` file and return the required result in a proper format

**Comment by enockzaake** [comment]
I would like to work on this

**Comment by ighoshsubho** [comment]
Sure go ahead! @enockzaake :)
