### ISSUE TITLE
Endpoint to calculate Roth IRA

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#191]
- This calculator estimates the balances of Roth IRA savings and compares them with regular taxable savings.
- Perform all the calculations in the `function.py` file present in the helpers folder
- Create the endpoint `roth-ira` in the `main.py` file and return the required result in a proper format

**Comment by itsmegarvi** [comment]
I am working on this

**Comment by itsmegarvi** [comment]
i have written the code in both main.py and functions.py but when checking on /docs after running the server it gives error

![image](https://user-images.githubusercontent.com/70941313/217212621-747148f0-1795-4e00-a0be-68da91d0b3ca.png)

I am not sure what am I doing wrong, can you help @ighoshsubho 

functions.py
`def roth_ira(
    principal: float,
    interest_rate: float,
    years: float,
    tax_rate: float,
    annual_contribution: float,
):
    roth_ira_balance = principal
    taxable_balance = principal
    for i in range(years):
        roth_ira_balance = (roth_ira_balance + annual_contribution) * (
            1 + interest_rate / 100
        )
        taxable_balance = (taxable_balance + annual_contribution) * (
            1 + interest_rate / 100 * (1 - tax_rate / 100)
        )
    return math.ceil(roth_ira_balance)`


main.py
`@app.get(
    "/roth-ira",
    tags=["Roth-IRA"],
    description="This calculator estimates the balances of Roth IRA savings and regular taxable savings.",
)
def roth_ira(
    principal: float,
    interest_rate: float,
    years: float,
    tax_rate: float,
    annual_contribution: float,
):
    try:
        roth_ira = functions.roth_ira(
            principal, interest_rate, years, tax_rate, annual_contribution
        )
        return {
            "Tag": "Roth-IRA",
            "Principal": principal,
            "Interest Rate": interest_rate,
            "Years": years,
            "Tax Rates": tax_rate,
            "Annual Contributions": annual_contribution,
            "Roth Ira Balance and Taxable savings balance": roth_ira,
        }
    except:
        return HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)
`

**Comment by itsmegarvi** [comment]
main.py
```@app.get(
    "/roth-ira",
    tags=["Roth-IRA"],
    description="This calculator estimates the balances of Roth IRA savings and regular taxable savings.",
)
def roth_ira(
    principal: float,
    interest_rate: float,
    years: float,
    tax_rate: float,
    annual_contribution: float,
):
    try:
        roth_ira = functions.roth_ira(
            principal, interest_rate, years, tax_rate, annual_contribution
        )
        return {
            "Tag": "Roth-IRA",
            "Principal": principal,
            "Interest Rate": interest_rate,
            "Years": years,
            "Tax Rates": tax_rate,
            "Annual Contributions": annual_contribution,
            "Roth Ira Balance and Taxable savings balance": roth_ira,
        }
    except:
        return HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)
```

**Comment by itsmegarvi** [comment]
```def roth_ira(
    principal: float,
    interest_rate: float,
    years: float,
    tax_rate: float,
    annual_contribution: float,
):
    roth_ira_balance = principal
    taxable_balance = principal
    for i in range(years):
        roth_ira_balance = (roth_ira_balance + annual_contribution) * (
            1 + interest_rate / 100
        )
        taxable_balance = (taxable_balance + annual_contribution) * (
            1 + interest_rate / 100 * (1 - tax_rate / 100)
        )
    return math.ceil(roth_ira_balance), math.ceil(taxable_balance)```

**Comment by ighoshsubho** [comment]
Ya, let me check @itsmegarvi

**Comment by ighoshsubho** [comment]
@itsmegarvi in the functions.py file the roth_ira_balance is not getting added over the years... You have run a for loop for the range of years but it has no direct effect with taxable balance or roth_ira_balance

**Comment by itsmegarvi** [comment]
@ighoshsubho I was compounding the interest per year as our principal gets increasing. So, the loop is just running for n years because the principal amount increases by annual_contribution every year and we get the interest for that amount. The answer matches the other available online calculators when run on an ide, so I am not sure about the error.
