### ISSUE TITLE
Endpoint to calculate Auto Lease

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#192]
- The Auto Lease Calculator can help estimate monthly lease payments based on total auto price or vice versa.
- Perform all the calculations in the `function.py` file present in the helpers folder
- Create the endpoint `auto-lease` in the `main.py` file and return the required result in a proper format

**Comment by helloshiv01** [comment]
Please assign me this issue

**Comment by ighoshsubho** [comment]
sure @helloshiv01! Go ahead! :)

**Comment by helloshiv01** [comment]
Done Kindly merge #194
