### ISSUE TITLE
Endpoint to calculate Personal Loan

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#199]
- The Personal Loan Calculator can give concise visuals to help determine what monthly payments and total costs will look like over the life of a personal loan.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `personal-loan` in the `main.py` file and return the required result in a proper format

**Comment by EdKsenia** [comment]
@ighoshsubho I want to make that endpoint, please assign me that task

**Comment by ighoshsubho** [comment]
sure @EdKsenia, go ahead!

**Comment by EdKsenia** [comment]
@ighoshsubho can you give me the permission to create a branche

**Comment by EdKsenia** [comment]
I figured it out, everything is fine

**Comment by ighoshsubho** [comment]
great!

**Comment by EdKsenia** [comment]
#209
