### ISSUE TITLE
Create issues and pull request template.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/fintech-api#2]
**Note**
+ Create an issue and pull request template for this project.
+ In the issue template, the user is to answer which endpoint he/she wants to add or which endpoint they found a bug.
+ In the PR template, ask them to link the corresponding issue, and ask questions like have you tested the output and if it is correct or not, and upload some screenshots if needed.

**Comment by itz-deepak** [comment]
assign this to me

**Comment by nikhil25803** [comment]
Go ahead @itz-deepak  :)
