### ISSUE TITLE
Add an endpoint to calculate Weighted Average Cost of Capital (WACC)

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#20]
**Note**

- The firm's overall cost of capital considering all of the components of the capital structure. 

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/wacc` in the `main.py` file with properly.

**Comment by pundarikaksha7** [comment]
I would like to take up this issue

**Comment by SpyzzVVarun** [comment]
Can I be assigned this issue?

**Comment by ighoshsubho** [comment]
Ya @pundarikaksha7, go ahead!

**Comment by ighoshsubho** [comment]
@SpyzzVVarun, you can work on other issues or simply raise an issue, and I will assign you to that.
