### ISSUE TITLE
Endpoint to calculate FHA Loan

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#200]
- FHA loans are mortgages insured by the Federal Housing Administration, the largest mortgage insurer in the world.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `fha-loan` in the `main.py` file and return the required result in a proper format

**Comment by ighoshsubho** [comment]
This is a friendly reminder that today is the last day to contribute to the Diversion event. We appreciate your participation and support in making this event a success.

Please make sure to submit your contributions by 6 PM today. Any submissions received after that time will not be accepted.

**Comment by Pritam991** [comment]
i want to working on this.

**Comment by thesourabhk** [comment]
@ighoshsubho  I have already created the functions but a bit adjustments and it will be ready to pull

**Comment by ighoshsubho** [comment]
since @Pritam991 asked for it, I would like to assign him the job, @thesourabhk you can raise an issue and I will assign you the job.
