### ISSUE TITLE
Endpoint to calculate Refinance

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#201]
- The refinance calculation can help plan the refinancing of a loan given various situations, and also allows the side-by-side comparison of the existing or refinanced loan.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `refinance` in the `main.py` file and return the required result in a proper format

**Comment by EdKsenia** [comment]
@ighoshsubho I want to make that endpoint, please assign me that task

**Comment by ighoshsubho** [comment]
go ahead @EdKsenia! :)

**Comment by EdKsenia** [comment]
pull request #220
