### ISSUE TITLE
Endpoint to calculate Credit Cards Payoff

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#202]
- This calculation creates a cost-efficient payback schedule for multiple credit cards using the Debt Avalanche method.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `credit-card-payoff` in the `main.py` file and return the required result in a proper format

**Comment by ighoshsubho** [comment]
This is a friendly reminder that today is the last day to contribute to the Diversion event. We appreciate your participation and support in making this event a success.

Please make sure to submit your contributions by 6 PM today. Any submissions received after that time will not be accepted.

**Comment by Aman1919** [comment]
i want to work on this

**Comment by ighoshsubho** [comment]
go ahead @Aman1919. :)
