### ISSUE TITLE
Endpoint to calculate Enterprise Value of a public company.

### ISSUE THREAD

**Issue by hfoley2013** [Clueless-Community/fintech-api#204]
### What bug or feature you wants to report.

Enterprise Value is the sum total of all ownership interests in a company and claims on its assets from both debt and equity holders. It is a critical number when evaluating the valuation multiples of publicly traded companies. 

The Enterprise Value is calculated as follows:
Enterprise Value = Equity Value + Total Debt + Preferred Stock + Non-controlling Interest - Cash & Cash Equivalents
Where Equity Value = Share Price x Fully Diluted Shares Outstanding

I will do the following:
- Add `calculate_enterprise_value` to `helpers/functions.py` to calculate Enterprise Value
- Add `calculate_enterprise_value` to `main.py`
- Add route, parameters, and sample output to `ENDPOINTS.md`
- Add test to `test_main.py` file

**Comment by ighoshsubho** [comment]
sure @hfoley2013, go ahead!
