### ISSUE TITLE
Add an endpoint to calculate Put-Call Parity

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#21]
**Note**

- Refers to the static price relationship between the prices of put and call options of an asset with the same strike price and expiration date.

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/put-call-parity` in the `main.py` file with properly.

**Comment by melencholicmice** [comment]
Hello , I would like to work on this issue , can younolease assign it to me.

**Comment by ighoshsubho** [comment]
ya @melencholicmice, go ahead

**Comment by melencholicmice** [comment]
Hello I have created the pull request #[31](https://github.com/Clueless-Community/fintech-api/pull/31) resolving this issue. Can you please review it.
Thank You
