### ISSUE TITLE
Endpoint to calculate Pension

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#218]
- There are mainly two options regarding how to receive income from a pension plan: either take it out as a lump sum payment or have it distributed in a stream of periodic payments until the retiree passes away (or in some cases, until both the retiree and their spouse passes away).
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `pension` in the `main.py` file and return the required result in a proper format

**Comment by animesharma3** [comment]
I am new to the project and I would like to contribute.

**Comment by animesharma3** [comment]
@ighoshsubho can you please assign me this issue?

**Comment by ighoshsubho** [comment]
sure @animesharma3, go ahead! :)

**Comment by Aman1919** [comment]
if there is no movement then i like to work on this

**Comment by ighoshsubho** [comment]
sure @Aman1919 go ahead! ;)

**Comment by NIveX2169** [comment]
Hi im gssoc 23 contributor new to open source can you elaborate what needs to be done here and can you assign the issue to me

**Comment by mridul45** [comment]
Greetings , I am a GSSOC 23 contributor . I find my skills to be a good match for the issue . Kindly accept me as a contributor.

**Comment by ighoshsubho** [comment]
This issue has been closed, please raise a new one and I will definitely assign you @mridul45 and @NIveX2169, and this project will be there in GSSOC'23.

**Comment by mridul45** [comment]
ok sure
