### ISSUE TITLE
Add an endpoint to calculate Variance of a Two Asset Portfolio

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#22]
**Note**

- Measures the fluctuation of the returns of a portfolio with two assets.

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/asset_portfolio` in the `main.py` file with properly.

**Comment by SpyzzVVarun** [comment]
I would like to work on this issue

**Comment by ighoshsubho** [comment]
Go ahead @SpyzzVVarun!
