### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by 584aditya** [Clueless-Community/fintech-api#224]
### What bug or feature you wants to report.

Hey Clueless Community,

I am Aditya and I am Interested to contribute my knowledge and practice to your project.
I am familiar with python, Tkinter, Database Programming in Python.

If in any kind of issue i can help please let me know

**Comment by mridul45** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by ighoshsubho** [comment]
@MihirCharan42, @584aditya and @mridul45, I'm raising some issues, just comment to assign you to that issue, I'll assign you accordingly!
