### ISSUE TITLE
Errors in main.py file

### ISSUE THREAD

**Issue by Codeansh** [Clueless-Community/fintech-api#227]
### What bug or feature you wants to report.

There are some errors in main.py file( like try except syntax error etc ), and the server is not starting.
Please assign this issue to me so that i can fix it.

**Comment by ighoshsubho** [comment]
Go ahead @Codeansh :)

**Comment by Codeansh** [comment]
Thanks @ighoshsubho, I am working on it.

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by Codeansh** [comment]
@ighoshsubho, I have already fixed this issue and raised a pull request. Please review my pull request.
