### ISSUE TITLE
Add an endpoint to calculate Duration With Convexity Adjustment

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#23]
**Note**

- Duration is the average time until all cash flows from a bond are delivered. The convexity adjustment helps determine the change in price that is not explained by duration.

- Create a function in `./helpers/functions.py` file for the calculation.

- Map it with an endpoint GET `/convexity_adjustment` in the `main.py` file with properly.

**Comment by DarK-VEnOM-16** [comment]
@ighoshsubho  I would like to work on this issue

**Comment by ighoshsubho** [comment]
Ya @DarK-VEnOM-16 go ahead!

**Comment by pundarikaksha7** [comment]
I would like to work on this issue

**Comment by pundarikaksha7** [comment]
Has this issue been resolved yet?

**Comment by pundarikaksha7** [comment]
Yes
