### ISSUE TITLE
Endpoint to calculate Social Security

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#230]
- While they are all useful, there currently isn't a way to help determine the ideal (financially speaking) age at which a person between the ages of 62-70 should apply for their Social Security retirement benefits.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `social_security` in the `main.py` file and return the required result in a proper format
- Update the `ENPOINTS.md` properly

**Comment by mridul45** [comment]
hi there , I believe that my skills can be a good match for the issue , as a GSSOC 23 member I ask you to assign me the issue.

**Comment by Codeansh** [comment]
I think I can do this. Please assign me this issue.

**Comment by ighoshsubho** [comment]
@mridul45 is the first one to comment, I'm assigning it to him, @Codeansh raise issue and I'll assign you with it!

**Comment by mridul45** [comment]
Hi I have completed both the tasks , I will make a pr tomorrow morning

**Comment by mridul45** [comment]
I have made the pr kindly look into it

**Comment by ighoshsubho** [comment]
Closing as done!
