### ISSUE TITLE
Add more unit-tests

### ISSUE THREAD

**Issue by Codeansh** [Clueless-Community/fintech-api#231]
### What bug or feature you wants to report.

In the code, more unit tests can be added in order to test the app more accurately.

**Comment by Codeansh** [comment]
Please assign me this issue.

**Comment by ighoshsubho** [comment]
Go ahead @Codeansh :) !

**Comment by Codeansh** [comment]
yes, its almost done.

**Comment by Codeansh** [comment]
Please review my PR, it's completed.
