### ISSUE TITLE
Gratuity Calculator

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/fintech-api#232]
Hi @ighoshsubho, I am a GSSOC'23 contributor

I would like to add a gratuity calculator for India, which calculates the amount that you would receive on quitting a job (if you have worked that job for atleast 5 years) using your last salary, tenure and other details. 

Kindly assign me this issue.

**Comment by ighoshsubho** [comment]
Sure, go ahead @DyuthiVivek! :)

**Comment by DyuthiVivek** [comment]
Hi @ighoshsubho I am submitting my pull request, but there are existing issues in th code
1. utils should be part of requirements.txt
2. an issue in utils:
 File "/home/dyuthi/girlscript/fintech-api/./helpers/utils.py", line 1, in <module>
    def percent_to_decimal(percent: int | float) -> float:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
3. issues in  test_certificate_of_deposit, test_simple_interest_rate_main and test_roi_main due to which the server is not running

Kindly help resolve these issues

**Comment by ighoshsubho** [comment]
Sure going through this and will merge accordingly! Thanks...

**Comment by ighoshsubho** [comment]
Closing as done!
