### ISSUE TITLE
Student loan Calculator

### ISSUE THREAD

**Issue by filza2112** [Clueless-Community/fintech-api#236]
### What bug or feature you wants to report.

* I want to create a Student Loan calculator which will help students manage a plan for their educational loan
* I will perform all the calculations in the `function.py` file present in the helpers folder
* I will create the endpoint `student-loan` in the `main.py` file and return the required result in a proper format
* I will also update the `ENPOINTS.md` properly

**Comment by filza2112** [comment]
please assign it to me under GSSoC'23

**Comment by ighoshsubho** [comment]
Sure go ahead @filza2112! :)

**Comment by filza2112** [comment]
@ighoshsubho Please check my PR #257
