### ISSUE TITLE
[documentation-readme file]

### ISSUE THREAD

**Issue by poorvika11** [Clueless-Community/fintech-api#238]
### What bug or feature you wants to report.

Readme file can be more interactive and comprehensive. Assign this task to me, I will do this

**Comment by ighoshsubho** [comment]
@poorvika11 thanks for raising this issue, it was much needed, You can add the Intro, its features, and the way to use. This will be of much help. You can refer the [scrapeUp](https://github.com/Clueless-Community/scrape-up) repository in ClueLess. Thanks. Assigning it to you. :)

**Comment by poorvika11** [comment]
Ohkayy, I will do it as suggested

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by ighoshsubho** [comment]
Hey @arunavabasu-03, you can raise a new issue and I will assign you with the same...

**Comment by poorvika11** [comment]
I will provide it by today EOD.

**Comment by poorvika11** [comment]
@ighoshsubho Please review the PR #293 and merge it.

**Comment by ighoshsubho** [comment]
Closing as done!
