### ISSUE TITLE
 Macaulay Duration

### ISSUE THREAD

**Issue by DyuthiVivek** [Clueless-Community/fintech-api#240]
### What bug or feature you wants to report.

Hi @ighoshsubho, I am a GSSOC'23 contributor

I would like to add a calculator for Macaulay Duration, which calculates the average number of years that an investor must maintain a position in the bond using the bond’s price, maturity, coupon and yield to maturity.

Kindly assign me this issue.

**Comment by ighoshsubho** [comment]
Go ahead @DyuthiVivek :)

**Comment by ighoshsubho** [comment]
@DyuthiVivek is it done?

**Comment by DyuthiVivek** [comment]
@ighoshsubho sorry for the delay, I will submit the pull request soon

**Comment by ighoshsubho** [comment]
Closing as done!
