### ISSUE TITLE
Endpoint For retirement Planning[ Gssoc'23]

### ISSUE THREAD

**Issue by kharshita590** [Clueless-Community/fintech-api#241]
### What bug or feature you wants to report.

I can Create an endpoint that calculates retirement savings projections based on inputs like current savings, annual contributions, expected return, and retirement age. It can provide estimates of future savings, income replacement ratio, and required savings to meet retirement goals

**Comment by ighoshsubho** [comment]
Go ahead @kharshita590 :)
