### ISSUE TITLE
Technical Indicator RSI

### ISSUE THREAD

**Issue by programerr01** [Clueless-Community/fintech-api#243]
### What bug or feature you wants to report.

can we add technical indicators too ?

**Comment by ighoshsubho** [comment]
As long as it satisfies financial needs you are much welcome! Go ahead @programerr01 :)

**Comment by ighoshsubho** [comment]
Is it done @programerr01 ?

**Comment by programerr01** [comment]
Yes, i have done it but i am thinking about not adding it to the project since it wouldn't fit very well with `financial calculations`.

**Comment by ighoshsubho** [comment]
Ok. Then if you are not merging then let me know I'll close the issue.
