### ISSUE TITLE
[FEATURE] Add Bond Equivalent Yield (GSSoC'23)

### ISSUE THREAD

**Issue by Archit-Kohli** [Clueless-Community/fintech-api#244]
### AIM ###
- Add a function to calculate bond equivalent yield

### DESCRIPTION ###
- Create a function to return bond equivalent yield
- Set up FastAPI Endpoint

**Comment by ighoshsubho** [comment]
sure @Archit-Kohli go ahead!

**Comment by ighoshsubho** [comment]
Closing as done!
