### ISSUE TITLE
[ISSUE TEMPLATE FILE]

### ISSUE THREAD

**Issue by adhikari-pratik** [Clueless-Community/fintech-api#246]
The template currently has grammatical errors which might not be pleasing towards contributions. 
I would fix it and make it more appealing. Can you please assign me this issue under GSSOC'23. Thank you!

**Comment by ighoshsubho** [comment]
Sure make it like other Repos in clueless-community! Go ahead @adhikari-pratik ;)

**Comment by adhikari-pratik** [comment]
Sorry for the delay. I will finish the task today.

**Comment by ighoshsubho** [comment]
Closing as done!
