### ISSUE TITLE
<commission calculator>

### ISSUE THREAD

**Issue by Pritam991** [Clueless-Community/fintech-api#256]
### What bug or feature you wants to report.

In sales, a commission is a form of payment that salespeople earn that is tied to how much of a service or a product they sell. Commissions are a method used to motivate salespeople, since the amount they sell directly impacts the amount that they can earn.

**Comment by ighoshsubho** [comment]
I think its already there, can you add anything new to it @Pritam991 ??

**Comment by Pritam991** [comment]
yeah its already there. okay i will contribute another.

close this issue.
