### ISSUE TITLE
End point to calculate Loan Affordability for any individual

### ISSUE THREAD

**Issue by Shivamjha12** [Clueless-Community/fintech-api#266]
### What bug or feature you wants to report.

 **I am a GSSOC'23 Contributor**

I want to create a endpoint Loan Affordability:
A loan affordability endpoint helps users to determine how much they can afford to borrow based on their income, interest rate and expenses. This feature help individuals to take right loan.

@ighoshsubho I love to work on this, kindly assign this to me.

**Comment by ighoshsubho** [comment]
Sure go ahead @Shivamjha12 :)
