### ISSUE TITLE
[BUG]Incorrect function name and accidental override

### ISSUE THREAD

**Issue by Nishith-Savla** [Clueless-Community/fintech-api#271]
## Current Behaviour 

Hey, I'm a GSSoC '23 Contributer and I found an issue.
The function for inflation is overridden by the effective annual rate function and hence the result in incorrect.

## Can you fix the bug by yourself?

- [x] YES
- [ ] NO

## Additional Information

The error can be seen here:
```
@app.get(
    "/effective_annual_rate",
    tags=["Effective Annual Rate"],
    description="Calculate Effective Annual Rate",
)
def inflation(annual_interest_rate: float, compounding_period: int):
```

**Comment by ighoshsubho** [comment]
Go ahead and solve the issue @Nishith-Savla ;)

**Comment by Nishith-Savla** [comment]
@ighoshsubho Seems it was fixed by someone else in some another PR.

**Comment by Nishith-Savla** [comment]
Sorry it was the other issue. My bad
