### ISSUE TITLE
[Feature] Move all the descriptions and tags to separate file to avoid redundancy

### ISSUE THREAD

**Issue by Nishith-Savla** [Clueless-Community/fintech-api#275]
## Are you adding a new feature?
- [ ] YES
- [x] NO

# Are you enhancing the old feature?
 - [x] YES
 - [ ] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature\enhancement.

Currently the list of endpoints shown on the index page has all the endpoints and their description hard coded which is duplicated in the particular function as well. 
To avoid this, we can create a separate dict or a json file having all the project routes, tags, description and take values from there.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
I'm a GSSoC '23 Contributer.

After the refactoring, the function decorator would be something like this.
```python
@app.get(CALCULATE_RETIREMENT_GOALS_ROUTE.name,
         tags=CALCULATE_RETIREMENT_GOALS_ROUTE.tags,
         description=CALCULATE_RETIREMENT_GOALS_ROUTE.description,
)
```

**Comment by ighoshsubho** [comment]
Sure go ahead @Nishith-Savla ;)

**Comment by ighoshsubho** [comment]
@Nishith-Savla is this done?

**Comment by Nishith-Savla** [comment]
Sorry @ighoshsubho. Didn't get time to work on this. Starting work now. Will get a PR ready in a week

**Comment by Nishith-Savla** [comment]
There are two functions for Calculating CAGR, should I remove one? If yes, which one?

**Comment by Nishith-Savla** [comment]
Another thing, from line 528, we are using hyphens instead of dashes. Do we want to keep it like that or make it consistent?
