### ISSUE TITLE
[Feature] Add Monte Carlo Simulation Functionality

### ISSUE THREAD

**Issue by Anantashayana** [Clueless-Community/fintech-api#276]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature\enhancement.

Requesting the addition of Monte Carlo simulation functionality to the Fintech API. This feature would enable users to perform advanced financial simulations and assess the probability distribution of investment returns or simulate various financial scenarios.

## Can you add the feature yourself?

- [x] YES
- [ ] NO

## Additional Information

- The addition of Monte Carlo simulation functionality will empower users with a powerful tool for advanced financial analysis, risk assessment, and decision-making. This feature would enhance the Fintech API's capabilities, attracting users seeking sophisticated financial modeling resources.
- I wanted to work on Monte Carlo Simulation for a long time. This will be the perfect opportunity to explore it and implement it. So I want you to assign this issue to me. 

Sincerely,
Anantashayana

**Comment by ighoshsubho** [comment]
Is this done @Anantashayana ?

**Comment by mridul45** [comment]
Hi there @ighoshsubho  I would delighted as GSSOC 23 contributor to work on the task as I am familiar with the concept.

**Comment by Anantashayana** [comment]
Thank You @ighoshsubho
