### ISSUE TITLE
[Feature] Endpoint for Calculating Book value per share

### ISSUE THREAD

**Issue by SohamD242** [Clueless-Community/fintech-api#279]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature\enhancement.

I would like create a Endpoint which calculate Book value per share (BVPS) based on inputs like total stockholders equity, value of preferred stock, Average number of outstanding shares.
It will provide exact Book value per share which can be used as an indicator of the value of company's stock

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I'm a GSSOC'23 contributor 
@ighoshsubho  Kindly assign it me.

**Comment by ighoshsubho** [comment]
Closed as done!
