### ISSUE TITLE
[Feature] <Endpoint for calculating Market Capitalization>

### ISSUE THREAD

**Issue by entrepreneur123** [Clueless-Community/fintech-api#287]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature/enhancement.
[I want to add the feature of market capitalization, so that user would be able to calculate marketcap value . ]

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
[@ighoshsubho , please assign this to me :)]

**Comment by ighoshsubho** [comment]
Sure @entrepreneur123 go ahead!

**Comment by ighoshsubho** [comment]
Closing as done!
