### ISSUE TITLE
[Feature] Endpoint to calculate accrued interest for a security that pays periodic interest

### ISSUE THREAD

**Issue by THEGAMECHANGER416** [Clueless-Community/fintech-api#295]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

A function to calculate the accrued interest for a security that pays periodic interest.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I would like to work on this issue under gssoc'23

**Comment by ighoshsubho** [comment]
Sure go ahead @THEGAMECHANGER416! ;)
