### ISSUE TITLE
Simple Personal savings Calculalor

### ISSUE THREAD

**Issue by filza2112** [Clueless-Community/fintech-api#300]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
This feature will calculate simple savings of an individual for a certain period of time 

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
* Will perform all the calculations in the `function.py` file present in helpers folder
* Will create the endpoint `simple_savings` in the `main.py` file and return the required result in a proper format
* Will update the `ENPOINTS.md` properly

**Comment by filza2112** [comment]
Please assign this to me

**Comment by ighoshsubho** [comment]
Go ahead @filza2112 ;)

**Comment by filza2112** [comment]
@ighoshsubho please check my PR #306
