### ISSUE TITLE
[Feature] Add black linter workflow

### ISSUE THREAD

**Issue by metabiswadeep** [Clueless-Community/fintech-api#307]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature/enhancement.

Add the black linter workflow to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
Go ahead @metabiswadeep ;)
