### ISSUE TITLE
[Feature] Adding endpoint for profit margin

### ISSUE THREAD

**Issue by ramya-kallam** [Clueless-Community/fintech-api#308]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
I want to add new endpoint for calculating profit margin. Profit margin is a financial ratio that measures the percentage of profit earned in relation to its revenue.
I would like to work on this feature under GSSoC'23. Thank you!

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
Sure @ramya-kallam go ahead!
