### ISSUE TITLE
[BUG] Unnecessary try block without except

### ISSUE THREAD

**Issue by Nishith-Savla** [Clueless-Community/fintech-api#314]
## Current Behaviour 
Code broken.

## Can you fix the bug by yourself?

- [x] YES
- [ ] NO

## Additional Information
The personal savings endpoint has a unnecessary try block and that too with a missing except block. Also, the variable names are incorrect. Seems that the commit is done in haste and the PR was not reviewed before merge.

Also, formatting is completely off, so will format the complete code in a new commit but same PR

PS: I'm a GSSoC '23 Contributer

**Comment by ighoshsubho** [comment]
Go ahead @Nishith-Savla ;)
