### ISSUE TITLE
Net Salary Calculator

### ISSUE THREAD

**Issue by filza2112** [Clueless-Community/fintech-api#317]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
A salary calculator which will calculate the total Salary of an employee taking cash bonus, stock bonus, tips etc as arguments 

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
* Will perform all the calculations in the `function.py` file present in helpers folder
* Will create the endpoint `calculate-salary` in the `main.py` file and return the required result in a proper format
* Will update the `ENPOINTS.md` properly

**Comment by filza2112** [comment]
@ighoshsubho please assign this to me

**Comment by ighoshsubho** [comment]
Sure go ahead @filza2112! ;)

**Comment by filza2112** [comment]
@ighoshsubho please check my PR #326
