### ISSUE TITLE
Add an endpoint to calculate Break Even Point

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#32]
**Note**
- Break even point is the point where a company's revenue equals it's costs.
![image](https://user-images.githubusercontent.com/89008784/206421827-7da14cac-f030-4796-ac24-d1b3b6e1e995.png)
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/bep` in the `main.py` file with properly.

**Comment by nikhil25803** [comment]
Go ahead @vamsikrishnarh7 : )
