### ISSUE TITLE
[Feature] Continuously Compounded Interest

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#322]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

Add a formula to calculate Continuously Compounded Interest which means that an account balance is constantly earning interest, as well as refeeding that interest back into the balance so that it, too, earns interest.
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I would like to work on this issue as a contribution for GSSOC'23

**Comment by ighoshsubho** [comment]
Closing this issue as the endpoint is redundant!
