### ISSUE TITLE
[Feature] Add a Loan To Value Ratio

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#324]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

Add a Loan to Value Ratio function that can be used by loan officers as part of evaluating an applicant's qualifications for automobile loans and mortgages.
LTV Ratio = (Loan Amount /  Value of Collateral)*100 
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

If considered as a good feature issue I would like to work on it as a contribution for GSSOC'23.

**Comment by ighoshsubho** [comment]
Sure @roberanegussie, go ahead with the issue ;)

**Comment by roberanegussie** [comment]
@ighoshsubho Kindly close the issue  I did it by mistake. Thanks.
