### ISSUE TITLE
Adding the try and except block in an endpoint

### ISSUE THREAD

**Issue by filza2112** [Clueless-Community/fintech-api#332]
<img width="679" alt="except" src="https://github.com/Clueless-Community/fintech-api/assets/115334313/67e6f8a6-1ba6-42bb-81ba-7aa1329b9ee1">
## Current Behaviour 
in main.py adding the try and except block in an endpoint

## Can you reproduce the bug
yes i will add the try and except block

## Can you fix the bug by yourself?

- [x] YES
- [ ] NO

**Comment by filza2112** [comment]
@ighoshsubho please assign it to me

**Comment by ighoshsubho** [comment]
Sure @filza2112 go ahead! ;)

**Comment by filza2112** [comment]
@ighoshsubho please check my PR #336
