### ISSUE TITLE
Add Endpoint to calculate Free Cash Flow to Equity

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#339]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

Free cash flow to equity (FCFE) is the amount of cash a business generates that is available to be potentially distributed to shareholders after accounting for the expenses to continue operations and future capital needs for growth.  

FCFE = Net Income + Depreciation & Amortization  –  CapEx  –  ΔWorking Capital + Net Borrowing

Net Income = Total Revenues – Total Expenses
Depreciation & Amortization = Initial cost of the asset / The lifetime of asset
CapEx = ΔPP&E + Current Depreciation
ΔWorking capital = Current assets - Current liabilities
Net Borrowing = Amount a company borrows - What debt it repays

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I am a GSSOC'23 contributor and want to work on this if it's considered a good issue.

**Comment by ighoshsubho** [comment]
Sure go ahead @roberanegussie ;)

**Comment by roberanegussie** [comment]
@ighoshsubho kindly close the issue as complete. Thanks.
