### ISSUE TITLE
Add an endpoint to calculate Price/Earning to ratio

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/fintech-api#34]
Note

Price/Earning ratio is the ratio between share price and the earing per share (EPS) .
![image](https://user-images.githubusercontent.com/44370586/206441008-3bcbcba8-090f-4e01-9959-b080ed20cf89.png)

Create a function in ./helpers/functions.py file for the calculation.
Map it with an endpoint GET /per in the main.py file with properly.

**Comment by hritikbhattacharya** [comment]
Assign this to me @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @hritikbhattacharya
