### ISSUE TITLE
Add Endpoint for Capital Gains Yield

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#352]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

I would like to add a feature that would calculate the Capital Gains Yield on a stock. 
The capital gains yield will equal a company's total stock return if a company does not pay dividends.
The formula for the capital gains yield is used to calculate the return on a stock based solely on the appreciation of the stock.
It can be calculated by using the following formula: (P1 - P0) / P0. 
P0 : Initial stock price where as P1: Stock price after first period.  
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I would like to work on this issue if its seen as a good one under GSSOC'23.

**Comment by roberanegussie** [comment]
Hello @ighoshsubho could you add a level to this issue. I am asking this to gain points in the leader board of GSSOC'23 once I make the PR. Thanks.

**Comment by ighoshsubho** [comment]
Closing as done!
