### ISSUE TITLE
Add Endpoint for Capitalization rate

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#356]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

I would like to add a feature to calculate the Capitalization Rate which is used in the world of commercial real estate to indicate the rate of return that is expected to be generated on a real estate investment.
This measure is computed based on the net operating income which is the annual income generated by the property after deducting all expenses that are incurred from operations including managing the property and paying taxes.
Capitalization rate is then calculated by dividing net operating income by current market value and is expressed as a percentage. 
Net Operating Income = Annual Income - Expenses
Capitalization Rate = Net Operating Income / Current Market Value
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I am a GSSOC'23 contributor and would like to work on this issue if approved and assigned.

**Comment by ighoshsubho** [comment]
Seems a it simple one, try to take more parameters and make it more meaningful. I've assigned! ;)

**Comment by roberanegussie** [comment]
@ighoshsubho I have added additional parameters based on your feedback such as rental_income, amenities, propertyManagement, propertyTaxes and insurance to be used as follows:

annual_income = rental_income + amenities,
expenses = propertyManagement + propertyTaxes + insurance. 

Then we can use the previous formulas 
Net Operating Income = Annual Income - Expenses
Capitalization Rate = Net Operating Income / Current Market Value.
