### ISSUE TITLE
[Feature]: add codeql workflow

### ISSUE THREAD

**Issue by harmeetsingh11** [Clueless-Community/fintech-api#362]
### Is your feature request related to a problem? Please describe.

The repository contains code in `python`, it does not have workflow for code scanning.

### Describe the solution you'd like

I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

### Record
- [x] I agree to follow this project's Code of Conduct 
- [x]  I'm a GSSoC'23 contributor
- [x]  I want to work on this issue

**Comment by ighoshsubho** [comment]
Hello @harmeetsingh11, this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.

**Comment by harmeetsingh11** [comment]
Thanks for letting me know @ighoshsubho. 

I have read `CONTRIBUTUING.md` but this workflow will remain same unless until tech stack of project will change. It will work for python. I think there is no need to make fresh PR.

Thanks
