### ISSUE TITLE
[Feature] Stock Price Prediction

### ISSUE THREAD

**Issue by Killer2OP** [Clueless-Community/fintech-api#366]
## Are you adding a new feature?
- [X] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [X] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [X] NO

## Describe your feature/enhancement.

Machine learning has significant applications in the stock price prediction. In this machine learning project, we will be talking about predicting the returns on stocks. This is a very complex task and has uncertainties. We will develop this project into two parts:

First, we will learn how to predict stock price using the LSTM neural network.
Then we will build a dashboard using Plotly dash for stock analysis.
## Can you add the feature by yourself?

- [X] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
This seems quite complex and interesting! Go ahead @Killer2OP ;)

**Comment by ighoshsubho** [comment]
Hello @Killer2OP , this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.

**Comment by pooranjoyb** [comment]
Can I start working on this as the PR as the previous PR is closed? @ighoshsubho

**Comment by Killer2OP** [comment]
> Can I start working on this as the PR as the previous PR is closed? @ighoshsubho

I am working on it.
