### ISSUE TITLE
Add calculate dividend payout ratio

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/fintech-api#38]
Note

The Dividend Payout Ratio (DPR) is the amount of dividends paid to shareholders in relation to the total amount of net income the company generates.
![image](https://user-images.githubusercontent.com/44370586/206660551-e654cc08-b1ae-4223-8664-b3a73405afbf.png)

Create a function in ./helpers/functions.py file for the calculation.
Map it with an endpoint GET /dividend_payout_ratio in the main.py file with properly.

**Comment by hritikbhattacharya** [comment]
Assign this @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead : )
