### ISSUE TITLE
[Feature] Functions to calculate profit and loss percentages

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [Clueless-Community/fintech-api#380]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature/enhancement.

Adding functions for profit and loss percentages.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
Hello @OMKAR-KALEPU, this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.
