### ISSUE TITLE
[BUG] Compund Annual Growth Rate Endpoint is defined twice

### ISSUE THREAD

**Issue by ritik48** [Clueless-Community/fintech-api#384]
## Current Behaviour 
'Compund Annual Growth Rate' Endpoint is defined twice

## Expected Behaviour
There should only be one endpoint for 'Compund Annual Growth Rate'

## Can you fix the bug by yourself?

- [x] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
Hello @ritik48, this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.

**Comment by ritik48** [comment]
@ighoshsubho please review this pr
