### ISSUE TITLE
[Feature] Add Endpoint for Debt-Service Coverage Ratio

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#385]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

I would like to add an endpoint to calculate Debt-Service Coverage Ratio.
The debt-service coverage ratio (DSCR) measures a firm's available cash flow to pay current debt obligations. 
The DSCR shows investors and lenders whether a company has enough income to pay its debts. 
DSCR = Net Operating Income / Total Debt Service
​where: Net Operating Income = Revenue− Operating Expenses
Total Debt Service = (Interest×(1−Tax Rate))+Principal

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I am a GSSOC'23 and would like to work on this issue if it is accepted.

**Comment by ighoshsubho** [comment]
Hello @roberanegussie, this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.
