### ISSUE TITLE
[Feature] Add Endpoint for Defensive Interval Ratio

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#388]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.

I want to add an endpoint to calculate Defensive Interval Ratio (DIR) which is is a financial liquidity ratio that indicates how many days a company can operate without needing to tap into capital sources other than its current assets. This can be viewed as how long a company can operate while relying only on liquid assets.
DIR (expressed as number of days) = Current Assets / Daily Operational Expenses
where:
           Current assets = cash + marketable securities + net receivables
           Daily Operational Expenses = (annual operating expenses - non_cash charges) / 365 
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information

I would like to work on this issue if it is approved under GSSOC'23.

**Comment by ighoshsubho** [comment]
Hello @roberanegussie, this is Version 2 of Fintech API repository, there had been few major updates, please go through the CONTRIBUTING.md to make further contributions. Thanks.
