### ISSUE TITLE
Endpoint to calculate and return Certificate of Deposit (CD)

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/fintech-api#4]
**Note**
+ A certificate of deposit is an agreement to make a fixed-term interest-bearing deposit of money.
+ Formula to calculate Certificate of Deposit

![image](https://user-images.githubusercontent.com/93156825/205441525-30f3dd40-dda1-486b-a891-5021c6757b31.png)

+ Create a function in `./helpers/functions.py` file for the calculation.
+ Map it with an endpoint  **GET** `/certificate_of_deposit` in the `main.py` file with properly.

**Comment by yixin0829** [comment]
Hi @nikhil25803 can I work on this issue?

**Comment by nikhil25803** [comment]
Sure @yixin0829 , go ahead :)
