### ISSUE TITLE
[Feature] Dark Mode

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/fintech-api#401]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [ ] NO

## Describe your feature/enhancement.
Change to dark Mode feature to enhance website
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
Assign this issue to me under GSSOC'23

**Comment by shraddha761** [comment]
@ighoshsubho please assign this issue to me

**Comment by ighoshsubho** [comment]
What dark mode are you talking about? Swagger UI??

**Comment by shraddha761** [comment]
@ighoshsubho toogle website in light as well as in dark mode

**Comment by ighoshsubho** [comment]
Sorry please go through the docs and first understand what's an API does, go through fastAPI and python and then contribute in this repo. Thanks.
