### ISSUE TITLE
[Feature] Compound Interest Calculator

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/fintech-api#402]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [x] YES
 - [ ] NO

## Describe your feature/enhancement.
A function that calculates the future value of an investment with compound interest. It should take into account the initial investment, interest rate, compounding frequency, and time period.
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
@ighoshsubho Assign this issue to me under GSSOC'23

**Comment by ighoshsubho** [comment]
Its already present as one of the endpoints.
