### ISSUE TITLE
[Feature] Rate of Return Calculator

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/fintech-api#403]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [ ] NO

## Describe your feature/enhancement.
A function that calculates the rate of return on an investment over a specific time period. It should consider both capital gains/losses and income generated from the investment.
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
Assign this issue to me under GSSOC'23

**Comment by ighoshsubho** [comment]
I'm assigning it to u, but try to include more parameters to make the endpoint useful.
