### ISSUE TITLE
[Feature] Return on Equity Endpoint

### ISSUE THREAD

**Issue by ritik48** [Clueless-Community/fintech-api#411]
## Are you adding a new feature?
- [x] YES
- [ ] NO

## Describe your feature/enhancement.
I want to add an endpoint to calculate return on equity.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

**Comment by ighoshsubho** [comment]
Check once if your endpoint matches with this endpoint `\roi_equity_funds`

**Comment by ritik48** [comment]
@ighoshsubho yes it seems it already exists. Will you please assign this issue to me #414
