### ISSUE TITLE
[Feature] Currency Conversion

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/fintech-api#418]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
Currency conversion is a fundamental feature in financial applications that allows users to convert an amount from one currency to another
## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
Assign this issue to me under GSSOC'23

**Comment by ighoshsubho** [comment]
How are you thinking of adding currency conversion?
