### ISSUE TITLE
Add an end point to calculate DTI

### ISSUE THREAD

**Issue by abinashrasonowal** [Clueless-Community/fintech-api#42]
Debt-to-income ratio (DTI) is all your monthly debt payments divided by your gross monthly income
Different  company has different DTIs as their minimum limit 
A person has to have a greater DTI than that limit in order to get a new loan

**Comment by nikhil25803** [comment]
Add this endpoint and make a PR @abinashrasonowal

**Comment by abinashrasonowal** [comment]
working on it
