### ISSUE TITLE
[Feature] Sharpe Ratio Calculation:

### ISSUE THREAD

**Issue by shraddha761** [Clueless-Community/fintech-api#424]
## Are you adding a new feature?
- [x] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [x] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [x] NO

## Describe your feature/enhancement.
sharpe_ratio(returns, risk_free_rate) - Calculate the Sharpe ratio, which measures the risk-adjusted return of an investment, based on the excess returns and the risk-free rate.

## Can you add the feature by yourself?

- [x] YES
- [ ] NO

## Additional Information
Assign this issue to me under GSSOC'23

**Comment by shraddha761** [comment]
@ighoshsubho no checked it

**Comment by ighoshsubho** [comment]
I think its already there.

![image](https://github.com/Clueless-Community/fintech-api/assets/93722719/1d709bd7-76b0-4cb4-8dc0-25d30324d49b)

**Comment by shraddha761** [comment]
@ighoshsubho ohh okk
