### ISSUE TITLE
Add missing Endpoints to index method

### ISSUE THREAD

**Issue by roberanegussie** [Clueless-Community/fintech-api#446]
## Describe about your issue.

In the  `main.py` file there are certain endpoints not added to the `def index` method such as 
`capitalization_rate; debt_service_coverage_ratio; accounts_payable_turnover_ratio; capm; defensive_interval_ratio; rate_of_return; financial_assest_ratio; cash_conversion_cycle; price_elasticity`
![image](https://github.com/Clueless-Community/fintech-api/assets/47657043/d1406615-b800-479e-a896-f47a3eea4c4d)
I would like to add those endpoints to the specified section in the file.
## Can you fix the issue by yourself?

- [x] YES
- [ ] NO

## Additional Information

I would like to work on this issue if it is accepted under GSSoC'23

**Comment by ighoshsubho** [comment]
@roberanegussie The same issue is mentioned in #390 and assigned to Codenash. Its still not done, if you want to work I can assign you with him.
