### ISSUE TITLE
Add a endpoint for fixed charge coverage ratio

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/fintech-api#45]
![image](https://user-images.githubusercontent.com/44370586/206778857-5a8e1eee-a6a1-4115-a940-aa22b574c8ab.png)

**Comment by hritikbhattacharya** [comment]
Assign this to me @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @hritikbhattacharya :)
