### ISSUE TITLE
Feature: Auto issue assign feature

### ISSUE THREAD

**Issue by andoriyaprashant** [Clueless-Community/fintech-api#452]
## Are you adding a new feature?
- [X] YES
- [ ] NO

# Are you enhancing the old feature?
 - [ ] YES
 - [X] NO

 ## Is your feature request related to a problem?
 - [ ] YES
 - [X] NO

## Describe your feature/enhancement.
By implementing the Auto Issue Assignment feature using GitHub Actions, the issue assignment process becomes automated and efficient. Issues matching specific comment-based criteria will be automatically assigned to the user who made the relevant comment, improving collaboration and task management within the repository.

## Can you add the feature by yourself?

- [X] YES
- [ ] NO

## Additional Information
GSSOC 2023

**Comment by andoriyaprashant** [comment]
Hey @ighoshsubho Please review my pull request #453 
Thank you

**Comment by andoriyaprashant** [comment]
Hey @ighoshsubho Can you please elaborate 
Thank you

**Comment by andoriyaprashant** [comment]
No problem Thank you @ighoshsubho

**Comment by ighoshsubho** [comment]
Closing then!
