### ISSUE TITLE
Add an endpoint to calculate Compound Interest.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/fintech-api#5]
**Note**
+ The cost of using borrowed money, or more specifically, the compensation a lender receives for lending money to a borrower, is known as compound interest.
+ Compound interest is calculated as 
![image](https://user-images.githubusercontent.com/93156825/205441724-6d522a5c-4f76-46d5-9f67-4505d8e78162.png)

+ Create a function in `./helpers/functions.py` file for the calculation.
+ Map it with an endpoint  **GET** `/compound_interest` in the `main.py` file with properly.

**Comment by melencholicmice** [comment]
Hello i would like to work on this issue. Can you please assign it to me.

**Comment by NiranjanHonnungar** [comment]
can i be assigned this issue?

**Comment by nikhil25803** [comment]
Go ahead @melencholicmice :)

**Comment by nikhil25803** [comment]
> can I be assigned this issue?

You may look into some other issue, or can even raise the issue to add a new endpoint.

**Comment by melencholicmice** [comment]
Hello I have created the pull request [#3](https://github.com/Clueless-Community/fintech-api/pull/15) resolving this issue. Can you please review it. If any more changes are required do let me know.
