### ISSUE TITLE
Add an endpoint to calculate Rule of 72

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#55]
**Note**
- The Rule of 72 helps you to estimate the number of years required to double your money at a given annual rate of return.
![image](https://user-images.githubusercontent.com/89008784/206898914-eea52d73-f302-4f1f-a55f-23c3ffd98f3e.png)
- Add an endpoint to calculate Rule of 72.
- Create a function in ``./helpers/functions.py`` file for the calculation.
- Map it with an endpoint GET ``/ruleof72`` in the ``main.py`` file with properly.

**Comment by vamsikrishnarh7** [comment]
@nikhil25803 Please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead :)

**Comment by nikhil25803** [comment]
@vamsikrishnarh7, any update?

**Comment by vamsikrishnarh7** [comment]
> @vamsikrishnarh7, any update?

About to make PR

**Comment by nikhil25803** [comment]
Okay :))
