### ISSUE TITLE
add an endpoint to calculate Capital Asset Pricing Model (CAPM)

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#56]
### What bug or feature you wants to report.

It helps to explain the relationship between excess market risk and expected return
 
<img width="265" alt="formula" src="https://user-images.githubusercontent.com/73659072/206902235-5aeef22f-7074-4e59-8839-df0250fe677a.png">

**Comment by ShamanthVallem** [comment]
@nikhil25803 Please assign me this issue

**Comment by nikhil25803** [comment]
Go ahead :)

**Comment by ShamanthVallem** [comment]
#63

**Comment by ShamanthVallem** [comment]
Made changes to endpoint.md and main.py
