### ISSUE TITLE
Add an endpoint to calculate Cost of Goods Sold

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#64]
**Note**
![image](https://user-images.githubusercontent.com/89008784/206907902-5d219e35-c5f5-4d29-beef-665c2484fc5f.png)
- Add an endpoint to calculate Free Cash Flow to Firm.
- Create a function in ``./helpers/functions.py`` file for the calculation.
- Map it with an endpoint GET ``/cogs`` in the ``main.py`` file with properly.

**Comment by vamsikrishnarh7** [comment]
@nikhil25803 Please assign this to me.

**Comment by nikhil25803** [comment]
Go ahead and add the endpoint :)
