### ISSUE TITLE
Add an endpoint to calculate Acid-Test Ratio

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#66]
**Note**
- The acid-test ratio, commonly known as the quick ratio, uses a firm's balance sheet data as an indicator of whether it has sufficient short-term assets to cover its short-term liabilities.

![image](https://user-images.githubusercontent.com/89008784/206908201-50f3e025-0717-45a9-8f46-2ec6c2d2a0d3.png)
- Add an endpoint to calculate Free Cash Flow to Firm.
- Create a function in ``./helpers/functions.py`` file for the calculation.
- Map it with an endpoint GET ``/acid-test-ratio`` in the ``main.py`` file with properly.

**Comment by vamsikrishnarh7** [comment]
@nikhil25803 Please assign this to me

**Comment by nikhil25803** [comment]
Looks good, add the endpoint and make a PR.
