### ISSUE TITLE
Add an endpoint to calculate Compounded Annual Growth Rate (CAGR)

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#73]
**Note**
**Formula:** `` CAGR=((FV/PV)^(1/n)) - 1`` 

- Where
``FV`` is **the investment's ending/maturity value**
``PV`` is **the investment's beginning/opening value**
``n`` is **the duration in years**
- Add an endpoint to calculate Compounded Annual Growth Rate (CAGR).
- Create a function in ``./helpers/functions.py`` file for the calculation.
- Map it with an endpoint GET ``/cagr`` in the ``main.py`` file with properly.

**Comment by nikhil25803** [comment]
Add the endpoint and make the PR.
