### ISSUE TITLE
Undefined variables in helpers/function.py and main.py files

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#84]
<img width="598" alt="issue1_fintech_helpers_functions" src="https://user-images.githubusercontent.com/73659072/207389268-8ece1a1b-2e68-4088-8d1d-1720c6be8aaa.png">
<img width="626" alt="isuue_2_main_py" src="https://user-images.githubusercontent.com/73659072/207389306-e42ec909-057e-45de-87fe-3080214d5d0e.png">

**Comment by nikhil25803** [comment]
Sure @ShamanthVallem , go ahead and make a PR :))

**Comment by ShamanthVallem** [comment]
made a PR #89
