### ISSUE TITLE
Add an endpoint to calculate Inflation rate

### ISSUE THREAD

**Issue by chandansgowda** [Clueless-Community/fintech-api#88]
<img width="640" alt="Screenshot 2022-12-15 at 9 20 23 AM" src="https://user-images.githubusercontent.com/41890434/207768354-5803c9b1-b692-4b97-b82e-20d3be4223d3.png">

**Comment by chandansgowda** [comment]
Shall I take this up?

**Comment by nikhil25803** [comment]
Go ahead and make a PR :))
