### ISSUE TITLE
Add an endpoint to calculate Current Ratio

### ISSUE THREAD

**Issue by vamsikrishnarh7** [Clueless-Community/fintech-api#92]
**Note**
The current ratio is a liquidity ratio that measures a company’s ability to pay short-term obligations or those due within one year.

`Current Ratio = current assets / current liabilities`
- Add an endpoint to calculate Current Ratio.
- Create a function in `./helpers/functions.py` file for the calculation.
- Map it with an endpoint GET `/current-ratio` in the `main.py` file with properly.

**Comment by nikhil25803** [comment]
Go ahead :))
