### ISSUE TITLE
Add an endpoint to calculate Herfindat index

### ISSUE THREAD

**Issue by ShamanthVallem** [Clueless-Community/fintech-api#94]
It is used to determine the competitiveness in a marketplace among different firms.
![IMG_20221216_023330](https://user-images.githubusercontent.com/73659072/207966996-a4dd5979-eb76-44cc-9b0a-d65ace471d7c.jpg)

**Comment by ShamanthVallem** [comment]
Please assign me this issue :)

**Comment by nikhil25803** [comment]
Go ahead :))

**Comment by ShamanthVallem** [comment]
Made a PR #99
